### ISSUE TITLE
PHP 8.2 issue? 

### ISSUE THREAD

**Issue by fredbradley** [spatie/lighthouse-php#9]
Awesome project. 

Installed it on PHP 8.1 all good. But then updated that machine's PHP to 8.2 using Remi-php docs. It gave me `8.2.1RC1` and I  receive the following error: 

```
Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "5". in /var/www/vhosts/lighthouse/vendor/symfony/process/Process.php:434 

Stack trace: 
 #0 /var/www/vhosts//lighthouse/vendor/symfony/process/Process.php(249): Symfony\Component\Process\Process->wait() 
 #1 /var/www/vhosts//lighthouse/vendor/spatie/lighthouse-php/src/Lighthouse.php(215): Symfony\Component\Process\Process->run() 
 #2 /var/www/vhosts//lighthouse/index.php(15): Spatie\Lighthouse\Lighthouse->run() 
 #3 {main} thrown in /var/www/vhosts//lighthouse/vendor/symfony/process/Process.php on line 434
```

Ran `composer update` - and nothing was found to update.  🤷‍♂️

**Comment by freekmurze** [comment]
I'm using this on PHP 8.2, so I don't think that's the problem.
